In [1]:
import pandas as pd

In [2]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [5]:
# on the left we see a range of numbers as an identifier for each row

In [6]:
# wanna view just the email addresses
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [ ]:
# want to se email addresses as the indexes for the dataframes
df.set_index('email')
# can see now that emails are at the left and are also bold

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [ ]:
df
# here it did not change, it still has the default indexes
# this si because pandas doesn't do all of these changes in place unless we specifically tell it to do

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [ ]:
df.set_index('email', inplace=True)
# now the changes will reflect even in the dataframe

In [10]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [11]:
df.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='str', name='email')

In [14]:
# why is this useful?
# the email addresses give a nice unique identifier
# previously while using .loc, we had to search from indexes (0,1,2,3...), which is tedious and hard to read
# having a unique identifier is always wayyy better
# now we can find a row by passing it's specifi label and it will be much more easy

In [16]:
df.loc['JaneDoe@email.com']

first    Jane
last      Doe
Name: JaneDoe@email.com, dtype: str

In [ ]:
# can also get specific values
df.loc['JaneDoe@email.com', 'last']
# df.loc[0] -> will give us an error, if we want to access using integer locations, use iloc

'Doe'

In [18]:
df.iloc[0]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: str

In [20]:
# to reset index
df.reset_index(inplace = True)
df

   index                    email  first     last
0      0  CoreyMSchafer@gmail.com  Corey  Schafer
1      1        JaneDoe@email.com   Jane      Doe
2      2        JohnDoe@email.com   John      Doe